server:
  port: 8080
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 510204441341-4q6ii1d78c18litpkprktg55v2f80fpr.apps.googleusercontent.com

